#!/usr/bin/env bash

pattern="^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_\/¯)(?<scope>\(\w+\)?((?=:\s)|(?=!:\s)))?(?<breaking>!)?(?<subject>:\s.*)?|^(?<merge>Merge \w+)"
if [[ ! $1 =~ $pattern ]]; then
    echo "The provided commit message doesn't follow Conventional Commits!"
    exit 1
fi
