#!/usr/bin/env bash

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" != "main" ]; then
  exit 0
fi

tag=$(git describe --tags --abbrev=0)
version=${tag:1} # truncate the starting `v`

IFS=. read -r major minor patch <<< "$version"

commits=$(git log -p --oneline origin/main..HEAD)
if $(echo $commits | grep -q '!|BREAKING');  then
    major=$((major+1))
elif $(echo $commits | grep -q 'feat');  then
    minor=$((minor+1))
elif $(echo $commits | grep -q 'fix');  then
    patch=$((patch+1))
else
    exit 0
fi

tag_next=$(printf "v%d.%d.%d" $major $minor $patch)

echo "Creating tag $tag_next"
git tag -m "$commits" $tag_next

source .git/hooks/post-commit.custom
